### PR TITLE
[CLEANUP] 

### PR DESCRIPTION
**Pull request by bradleypriest**
This is a cleanup PR for the API documentation to help us get back on track.
It can't be merged as a PR as it has been rebuild on top of upstream/master and will require force-pushing new-master over the current master when approved.

- [x] Rebuild back on top of upstream master (Slate 2.0)
- [x] Intro + API restructure and copy tweak
- [x] Add in first proper guide
- [x] Misc cleanups

#### To review
Read through copy up until resources section.
Designer to help fix up the `aside`'s UI.

Here's is the recent changes I've made: https://github.com/tradegecko/smaug/compare/c507d02b7b33a2f165c58ba2b2cde619aafdb690...bcab083981e5c3c8b0681efbcddb61e5cb7d3f8e . 
However, I may have made a couple of (mostly CSS) rebase mistakes.

#### Next Steps (future PRs)
- Fulfilling a Sales Order guide
- Order Actions guide cleanup
- Seperate changelog and deprecated functionality sections
- Reboot changelog with the last 2-4 quarter's changes only

### CODE REVIEW

**Comment by bradleypriest** [comment]
@MohammadHabbab @RenchChua @ShindoSensei ping

**Comment by MohammadHabbab** [comment]
@bradleypriest on my side, I'll review it over the weekend, and will submit feedback before Monday.
@RenchChua and @ShindoSensei ETA ?

**Comment by bradleypriest** [comment]
Honestly, biggest piece is if someone can get it running with one of the design team so they can side by side it. Should be a quick job

**Comment by ShindoSensei** [comment]
@MohammadHabbab We're blocking out some time with design to get this done side-by-side with a designer early next week. ETA aiming for end Tuesday to finish review & fixes

**Comment by RenchChua** [comment]
Have gone through this with Craig, identified a few design issues that would need fixing. It's on Craig's backlog. He'll be working on them over the next couple of days. Will follow up.

**Comment by bradleypriest** [comment]
@craigmassingham are the changes fixes to bring this up to the state of the existing docs, or improvements across both, would be nice to get this back to parity, get it live and then start working on improvements

**Comment by craigmassingham** [comment]
Alert, nav, section changes will be across all. Mainly colour and spacing changes.

Yep, get live and I can update later.

I can do a review of issues at the same time.

**Pull request merged**
