### PR TITLE
Remove endpoints not in the gem

### PR DESCRIPTION
**Pull request by lcpriest**
I am a little sad about this, I really liked the idea of "Anything we can do, you can do".

I'm happy to put these in the gem (minus price lists), or have a chat about what they need to join the rest of the API in being public.

### CODE REVIEW

**Comment by lcpriest** [comment]
Ping @bradleypriest

**Comment by bradleypriest** [comment]
But you understand why though right?
We are going to be completely rewriting these APIs sometime soon and don't want to have to version our API just for that.

**Comment by lcpriest** [comment]
What are we changing in stock transfers and stock adjustments? 
I think Tax Components is a good API as it is currently.
Price Lists definitely.

**Comment by bakura10** [comment]
Hi !

What is preventing stock adjustment API to be available? I absolutely need it, it works pretty nice and the API is convenient as well. Any thoughts n this?

**Comment by bradleypriest** [comment]
Hi @bakura10, any non-documented APIs are still subject to large changes, we haven't finalized the structure of the StockAdjustment API, so we don't want to publicly document it just yet.
You're welcome to use it, and we'll do our best to notify our developers before any major breaking changes of even our non-documented APIs

**Comment by bakura10** [comment]
I definitely understand that behaviour, but those are pretty important API and are the base of the product. This discussion is more than 1 year old, it would be good to have those base blocks documented and safe to use. Otherwise I'd suppose versioning the API would be a good work-around as well (although I undertsand the complexities being this).

**Comment by bradleypriest** [comment]
Hi @bakura10, completely understand, and underneath we do have the structure for versioning, but we don't want to add that complexity until absolutely necessary.

Our core APIs around Inventory, Relationships and Orders were our primary push.
We look forward to finalizing the APIs when we tackle the Stock Adjustment section next.

But in the meantime, as I said, you're very welcome to use the APIs as they are.

**Comment by bakura10** [comment]
Thanks a lot!

Apparently the place where you announce changes is this right: https://groups.google.com/forum/?hl=en#!forum/tradegecko-api-developers ?

I've applied more than 1 week ago but it seems that I've not been accepted yet. Is there any better palce to be informed?

**Comment by gherry** [comment]
@bakura10 I just added you into the group

**Pull request merged**
